using Microsoft.AspNetCore.Mvc;
using PottaAPI.Models;
using PottaAPI.Models.Common;
using PottaAPI.Services.Interfaces;

namespace PottaAPI.Controllers
{
    /// <summary>
    /// Staff authentication for the mobile app. Staff log in using a daily rotating code
    /// generated by the desktop app. No CRUD — staff management is desktop-only.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class StaffController : ControllerBase
    {
        private readonly IStaffService _staffService;

        public StaffController(IStaffService staffService)
        {
            _staffService = staffService;
        }

        /// <summary>Authenticate a staff member using their daily code.</summary>
        /// <remarks>
        /// The daily code is a short rotating code generated by the desktop app each day.
        /// On success, returns the staff member's profile and role.
        /// On failure, still returns HTTP 200 with <c>success: false</c> — check the <c>success</c> field.
        /// </remarks>
        /// <response code="200">Login result (check <c>success</c> field — false means wrong/expired code)</response>
        /// <response code="400">Daily code was not provided</response>
        [HttpPost("login")]
        [ProducesResponseType(typeof(StaffLoginResponse), 200)]
        [ProducesResponseType(typeof(StaffLoginResponse), 400)]
        public async Task<ActionResult<StaffLoginResponse>> Login([FromBody] StaffLoginRequest request)
        {
            if (string.IsNullOrWhiteSpace(request?.DailyCode))
            {
                return BadRequest(new StaffLoginResponse
                {
                    Success = false,
                    Message = "Daily code is required"
                });
            }

            var response = await _staffService.LoginWithDailyCodeAsync(request.DailyCode);
            
            if (!response.Success)
            {
                return Ok(response); // Return 200 with success=false for invalid credentials
            }

            return Ok(response);
        }

        /// <summary>Get all active staff members (for server transfer, etc.).</summary>
        /// <remarks>
        /// Returns basic staff information without daily codes for security.
        /// Use this endpoint to display a list of available staff when transferring servers.
        /// </remarks>
        /// <response code="200">List of active staff members</response>
        /// <response code="500">Database error</response>
        [HttpGet]
        [ProducesResponseType(typeof(ApiResponseDto<List<StaffListDto>>), 200)]
        [ProducesResponseType(500)]
        public async Task<ActionResult<ApiResponseDto<List<StaffListDto>>>> GetAllStaff()
        {
            try
            {
                var staff = await _staffService.GetAllActiveStaffAsync();
                
                return Ok(new ApiResponseDto<List<StaffListDto>>
                {
                    Success = true,
                    Message = "Staff retrieved successfully",
                    Data = staff
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new ApiResponseDto<List<StaffListDto>>
                {
                    Success = false,
                    Message = $"Failed to retrieve staff: {ex.Message}",
                    Data = new List<StaffListDto>()
                });
            }
        }

        /// <summary>Check whether a daily code is valid and not yet expired.</summary>
        /// <param name="code">The daily code to validate</param>
        /// <response code="200">Validation result with <c>isValid</c> flag and expiry info</response>
        /// <response code="400">Code was not provided</response>
        [HttpGet("validate/{code}")]
        [ProducesResponseType(typeof(CodeValidationResponse), 200)]
        [ProducesResponseType(400)]
        public async Task<ActionResult<CodeValidationResponse>> ValidateCode(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                return BadRequest(new CodeValidationResponse
                {
                    IsValid = false,
                    Message = "Daily code is required"
                });
            }

            var response = await _staffService.ValidateCodeAsync(code);
            return Ok(response);
        }

        /// <summary>Get the QR code payload for a staff member so the desktop can display it.</summary>
        /// <remarks>
        /// The QR code encodes the staff's daily code and the API base URL so the mobile app
        /// can scan it to log in without typing anything.
        /// </remarks>
        /// <param name="staffId">Numeric staff ID</param>
        /// <response code="200">QR code data including the encoded string and display URL</response>
        /// <response code="404">Staff member not found</response>
        [HttpGet("qr-data/{staffId}")]
        [ProducesResponseType(typeof(StaffQRCodeResponse), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<StaffQRCodeResponse>> GetQRCodeData(int staffId)
        {
            // Get base URL from request
            var apiUrl = $"{Request.Scheme}://{Request.Host}/api";
            
            var response = await _staffService.GetStaffQRCodeDataAsync(staffId, apiUrl);
            
            if (!response.Success)
            {
                return NotFound(response);
            }

            return Ok(response);
        }

        /// <summary>Look up a staff member's profile by their daily code without recording a login.</summary>
        /// <remarks>Useful for displaying staff info on a confirmation screen before committing to login.</remarks>
        /// <param name="code">The daily code</param>
        /// <response code="200">Staff profile</response>
        /// <response code="400">Code not provided</response>
        /// <response code="404">No staff found for that code</response>
        [HttpGet("info/{code}")]
        [ProducesResponseType(typeof(StaffDTO), 200)]
        [ProducesResponseType(400)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<StaffDTO>> GetStaffByCode(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                return BadRequest(new { message = "Daily code is required" });
            }

            var staff = await _staffService.GetStaffByCodeAsync(code);
            
            if (staff == null)
            {
                return NotFound(new { message = "Staff member not found" });
            }

            return Ok(staff);
        }
    }
}
